create index employees_i on employees ( empid,email,salary, deptno, mgrid );
create index CATEGORY_i on CATEGORY (category_main, sub_category );
create index customers_i on customers ( customer_email, customerid );
create index deliveredby_i on deliveredby (orderid);
create index deliverypartner_i on deliverypartner ( partner_id );
create index department_i on department ( deptno );
create index inventory_i on inventory ( inventory_id);
create index inventory_product_i on inventory_product ( productid );
create index order_items_i on order_items ( orderid, productid, product_price);
create index orders_i on orders ( orderid,transaction_id);
create index product_i on product (productid, price);
create index returns_i on returns ( orderid, customerid, product_id);
create index transactions_i on transactions ( orderid, payment_status);